spring-cloud/spring-cloud-contract

- circle.yml
- docs/src/main/asciidoc/verifier/stubrunner.adoc
- pom.xml
- samples/standalone/dsl/http-client/src/test/java/com/example/loan/LoanApplicationServiceTests.java
- samples/standalone/dsl/http-client/src/test/resources/application-test-repo.yaml
- samples/standalone/dsl/http-client/src/test/resources/application.yaml
- samples/standalone/messaging/stream-sink/src/test/resources/application.yml
- spring-cloud-contract-stub-runner/README.adoc
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/AetherStubDownloader.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/StubRunnerFactory.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/junit/StubRunnerRule.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/spring/AutoConfigureStubRunner.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/spring/StubRunnerConfiguration.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/spring/StubRunnerProperties.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/spring/cloud/StubMapperProperties.java
- spring-cloud-contract-stub-runner/src/test/groovy/org/springframework/cloud/contract/stubrunner/junit/StubRunnerRuleCustomPortJUnitTest.java
- spring-cloud-contract-stub-runner/src/test/groovy/org/springframework/cloud/contract/stubrunner/junit/StubRunnerRuleJUnitTest.java
- spring-cloud-contract-stub-runner/src/test/groovy/org/springframework/cloud/contract/stubrunner/junit/StubRunnerRuleSpec.groovy
- spring-cloud-contract-stub-runner/src/test/groovy/org/springframework/cloud/contract/stubrunner/server/StubRunnerBootSpec.groovy
- spring-cloud-contract-stub-runner/src/test/groovy/org/springframework/cloud/contract/stubrunner/spring/StubRunnerConfigurationSpec.groovy
- spring-cloud-contract-stub-runner/src/test/groovy/org/springframework/cloud/contract/stubrunner/spring/cloud/StubRunnerSpringCloudAutoConfigurationSpec.groovy
- spring-cloud-contract-stub-runner/src/test/groovy/org/springframework/cloud/contract/stubrunner/spring/cloud/StubRunnerSpringCloudAutoConfigurationWithoutDiscoverySpec.groovy
- spring-cloud-contract-stub-runner/src/test/resources/application-test.yml
- spring-cloud-contract-stub-runner/src/test/resources/application.yml
- spring-cloud-contract-stub-runner/src/test/resources/logback.xml
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/test/resources/functionalTest/bootSimple/src/test/resources/logback-test.groovy
- tests/spring-cloud-contract-stub-runner-camel/src/test/resources/application.yml
- tests/spring-cloud-contract-stub-runner-integration/src/test/groovy/org/springframework/cloud/contract/stubrunner/messaging/integration/IntegrationStubRunnerSpec.groovy
- tests/spring-cloud-contract-stub-runner-integration/src/test/resources/application.yml
- tests/spring-cloud-contract-stub-runner-stream/src/test/resources/application.yml
it's much easier to pass props via the annotation instead of property files. With this change the user can provide the properties inside the test via the annotation. The only thing that has to be passed via props is repositoryRoot (typically it's a very constant property that you set once).
fixes #46
cc @dsyer 
BTW for some reason I couldn't make `repositoryRoot` set via the annotation. Even if I made it a String. What always was taken was the default value. Strange...
> Added options to pass props via @AutoConfigureStubRunner

- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/groovy/org/springframework/cloud/contract/verifier/plugin/SpringCloudContractVerifierGradlePlugin.groovy
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/test/groovy/org/springframework/cloud/contract/verifier/plugin/ContractVerifierSpec.groovy
Updated plugin to explicitly include Gradle Groovy plugin, so that this plugin can properly evaluate when included in a Gradle project that does not currently apply the Groovy plugin. Additionally, added unit tests to verify functionality provided by the plugin. Fixes gh-65
> Updated plugin to explicitly include Gradle Groovy plugin

- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/RegexPatterns.groovy
- spring-cloud-contract-spec/src/test/groovy/org/springframework/cloud/contract/spec/internal/RegexPatternsSpec.groovy
fixes #113 
Not sure if this regex is as inclusive as necessary, but it covers `java.util.UUID::randomUUID`
> Add UUID regex compatible with java.util.UUID.

- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/ExecutionProperty.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/JUnitMessagingMethodBodyBuilder.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/JUnitMethodBodyBuilder.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/MethodBodyBuilder.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/RequestProcessingMethodBodyBuilder.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/SpockMessagingMethodBodyBuilder.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/SpockMethodRequestProcessingBodyBuilder.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/ContractHttpDocsSpec.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/MockMvcMethodBodyBuilderSpec.groovy
Fixes #111.
Currently `MethodBodyBuilder::getTestSideValue` returns a String without quotes around it.
If the server value is a static string, it returns the static string wrapped in double quotes.
If the server value is an `ExecutionProperty` instance, it returns the command's code unquoted.
> Allow MethodBodyBuilder to evaluate ExecutionProperty objects

- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/StubRunnerExecutor.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/server/TriggerController.java
- spring-cloud-contract-stub-runner/src/test/groovy/org/springframework/cloud/contract/stubrunner/server/StubRunnerBootSpec.groovy
without this whenever sth went wrong we got a 404 and message in logs in debug
with this change we explicitly say what went wrong and return the list of possible labels
fixes #118
> Throw explicit exceptions for stub runner boot

- docs/src/main/asciidoc/spring-cloud-contract.adoc
- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/messaging/amqp/ContractVerifierAmqpAutoConfiguration.java
- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/messaging/amqp/MessageListenerAccessor.java
- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/messaging/amqp/SpringAmqpStubMessages.java
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/messaging/amqp/MessageListenerAccessorSpec.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/messaging/amqp/SpringAmqpStubMessagesSpec.groovy
- tests/spring-cloud-contract-stub-runner-amqp/README.adoc
- tests/spring-cloud-contract-stub-runner-amqp/src/main/java/org/springframework/cloud/contract/stubrunner/messaging/amqp/AmqpMessagingApplication.java
- tests/spring-cloud-contract-stub-runner-amqp/src/main/java/org/springframework/cloud/contract/stubrunner/messaging/amqp/MessageSubscriber.java
- tests/spring-cloud-contract-stub-runner-amqp/src/main/java/org/springframework/cloud/contract/stubrunner/messaging/amqp/MessageSubscriberRabbitListener.java
- tests/spring-cloud-contract-stub-runner-amqp/src/test/groovy/org/springframework/cloud/contract/stubrunner/messaging/amqp/AmqpStubRunnerRabbitListenerSpec.groovy
I improved the first version of the spring-ampq integration by adding support for multiple listener containers on the application context and also for `@RabbitListener` annotated endpoints.
Let me know what you think.
I am trying to get some feedback from the spring-amqp team via gitter as well.
> add support for spring-amqp annotated listener endpoints

- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/messaging/amqp/ContractVerifierAmqpAutoConfiguration.java
- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/messaging/amqp/RabbitMockConnectionFactoryAutoConfiguration.java
- tests/samples-messaging-amqp/src/test/groovy/com/example/AmqpMessagingApplicationSpec.groovy
- tests/spring-cloud-contract-stub-runner-amqp/README.adoc
- tests/spring-cloud-contract-stub-runner-amqp/src/test/resources/application.yml
Fixes #131
Changed the conditions to apply the amqp integration auto configuration as follows:
```
@ConditionalOnClass(RabbitTemplate.class)
@ConditionalOnProperty(name="stubrunner.amqp.enabled", havingValue="true")
```
Also changed the property name for the `RabbitMockConnectionFactoryAutoConfiguration` from `verifier.amqp.mockConnection` to `stubrunner.amqp.mockConnection` to use a common prefix.
```
@ConditionalOnProperty(value = "stubrunner.amqp.mockConnection", havingValue = "true", matchIfMissing = true)
```
> enable amqp integration by property (#131)

- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/ClientDslProperty.groovy
- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/Common.groovy
- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/DslProperty.groovy
- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/Headers.groovy
- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/HttpHeaders.groovy
- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/HttpMethods.groovy
- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/MediaTypes.groovy
- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/PatternValueDslProperty.groovy
- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/RegexPatterns.groovy
- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/Request.groovy
- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/Response.groovy
- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/ServerDslProperty.groovy
- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/util/RegexpUtils.groovy
- spring-cloud-contract-stub-runner/src/test/resources/repository/contracts/contract1.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/util/RegexpBuilders.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/ContractHttpDocsSpec.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/JaxRsClientMethodBuilderSpec.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/MockMvcMethodBodyBuilderSpec.groovy
- tests/samples-messaging-camel/src/test/groovy/com/example/CamelMessagingApplicationSpec.groovy
With this change to DSL we're adding some helper methods
`c(...)` / `p(...)` - for consumer / producer
Example:
```
Contract contractDsl = Contract.make {
request {
method "GET"
url "test"
}
response {
status 200
body(
property1: "a",
property2: $(
c('123'),
p(regex('[0-9]{3}'))
)
)
headers {
header('Content-Type': 'application/json')
}
}
}
```
so 
- instead of `consumer()` you can write `c()`
- instead of `producer()` you can write `p()`
example
```
Contract contractDsl = Contract.make {
request {
method 'GET'
urlPath '/get'
body([
alpha: $(anyAlphaUnicode()),
number: $(anyNumber()),
aBoolean: $(aBoolean()),
ip: $(anyIpAddress()),
hostname: $(anyHostname()),
email: $(anyEmail()),
url: $(anyUrl()),
uuid: $(anyUuid())
])
headers {
contentType(applicationJson())
}
}
response {
status 200 …
```
> Simplification of the dsl

- spring-cloud-contract-stub-runner/README.adoc
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/spring/StubRunnerConfiguration.java
- spring-cloud-contract-stub-runner/src/test/groovy/org/springframework/cloud/contract/stubrunner/spring/StubRunnerConfigurationSpec.groovy
without this change you can't reference the port of a server as an env var
fixes #147
> Adds the env prop for every run server

- docs/src/main/asciidoc/verifier/contract.adoc
- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/BodyMatcher.groovy
- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/BodyMatchers.groovy
- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/Input.groovy
- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/MatchingType.groovy
- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/OptionalProperty.groovy
- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/OutputMessage.groovy
- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/Request.groovy
- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/Response.groovy
- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/ResponseBodyMatchers.groovy
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/messaging/camel/StubRunnerCamelPredicate.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/messaging/integration/StubRunnerIntegrationMessageSelector.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/messaging/stream/StubRunnerStreamMessageSelector.java
- spring-cloud-contract-stub-runner/src/test/groovy/org/springframework/cloud/contract/stubrunner/messaging/camel/StubRunnerCamelPredicateSpec.groovy
- spring-cloud-contract-stub-runner/src/test/groovy/org/springframework/cloud/contract/stubrunner/messaging/integration/StubRunnerIntegrationMessageSelectorSpec.groovy
- spring-cloud-contract-stub-runner/src/test/groovy/org/springframework/cloud/contract/stubrunner/messaging/stream/StubRunnerStreamMessageSelectorSpec.groovy
- spring-cloud-contract-tools/spring-cloud-contract-converters/src/test/groovy/org/springframework/cloud/contract/verifier/wiremock/DslToWireMockClientConverterSpec.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/JaxRsClientSpockMethodRequestProcessingBodyBuilder.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/MessagingMethodBodyBuilder.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/MethodBodyBuilder.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/RequestProcessingMethodBodyBuilder.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/dsl/wiremock/WireMockRequestStubStrategy.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/util/JsonToJsonPathsConverter.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/MockMvcMethodBodyBuilderWithMatchersSpec.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/util/JsonToJsonPathsConverterSpec.groovy
Without this change we're forcing users to embed their dynamic properties inside the body. For some this is natural and acceptable, but especially for the users coming from the Pact world this sounds bizarre. Also some other people have a problem with remembering who the consumer / producer is etc.
With this change we're introducing the `stubMatchers` and `testMatchers` section. Thanks to this one can separate the body from defining the dynamic properties. Especially for Pact users this is more natural. Speaking of which this is a prerequisite for https://github.com/spring-cloud/spring-cloud-contract/issues/96
fixes #185
> Stub / Test Matchers

- docs/src/main/asciidoc/verifier/contract.adoc
- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/MatchingType.groovy
- spring-cloud-contract-spec/src/test/groovy/org/springframework/cloud/contract/spec/internal/MatchingTypeSpec.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/BlockBuilder.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/MethodBodyBuilder.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/util/JsonToJsonPathsConverter.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/MockMvcMethodBodyBuilderWithMatchersSpec.groovy
without this change it's impossible to assert with response matchers all elements of an array
with this change we're using AssertJs conditions in case the pattern contains [*]
fixes #217
> Adding an option to validate children nodes in an array

- spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockConfiguration.java
- spring-cloud-contract-wiremock/src/test/java/org/springframework/cloud/contract/wiremock/AutoConfigureWireMockFilesApplicationWithoutSlashTests.java
- spring-cloud-contract-wiremock/src/test/java/org/springframework/cloud/contract/wiremock/AutoConfigureWireMockStubsApplicationWithSlashTests.java
without this change the pattern for stubs contains an unnecessary / which corrupts the location search (e.g. /_files is converted to //_files and there is no such path)
with this change we're removing that value
fixes #216
> Fixed unnecessary slash

- docs/src/main/asciidoc/spring-cloud-wiremock.adoc
Fixed the code example typo: from "status" to "status()"
> Fixed a typo in docs

- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/FileSaver.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/TestGenerator.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/JavaTestGenerator.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/SingleTestGenerator.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/config/TestFramework.groovy
without this change it's impossible to change the generated file extension
with this change you can do it. E.g. provide your own test generator that will store files in `.php` file
fixes #253
> Adding an option to override file extension

- docs/src/main/asciidoc/verifier/introduction.adoc
Per the conversation in Gitter today, a PR with a FAQ update.  I don't know how to test the generated documentation outside of just looking at the adoc rendering in Intellij, so just a heads up incase I've done something that formats terribly ;)
> gh-258: Added logging config for debugging to FAQ

- README.adoc
The `RestAssured` framework mistakenly named `RestEasy` in the documentation. :-)
> Fix typo in the docs, add links to MockMvc and RestAssured docs

- docs/src/main/asciidoc/spring-cloud-wiremock.adoc
I believe this was meant to enumerate Spring REST Docs supported technologies. If so, then it should be Rest Assured here.
> Spring REST Docs integration docs fix

- docs/src/main/asciidoc/spring-cloud-wiremock.adoc
Adding a link to the `publishing stubs as JARs` section in the REST Docs stubs generation docs.
> Additional linking between sections in REST Doc documentation

- docs/src/main/asciidoc/spring-cloud-wiremock.adoc
- spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/restdocs/ContractDslSnippet.java
- spring-cloud-contract-wiremock/src/test/java/org/springframework/cloud/contract/wiremock/restdocs/ContractDslSnippetTests.java
This PR removes unnecessary host entries from Spring REST Docs-generated request contracts:
1. scheme, host and port parts of the url
2. Host header
3. Content-Length header
All seem not be needed and could just cause problems with the contract.
This PR is the same as #292 but with fixes applied and targeted at 1.0.x branch.
Issue #290 was already closed (by mistake I guess) and it is still valid.
Closes #290
> Remove unnecessary host entry from Spring REST Docs contract generation

- spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/restdocs/WireMockSnippet.java
- spring-cloud-contract-wiremock/src/test/java/org/springframework/cloud/contract/wiremock/restdocs/WireMockSnippetTests.java
It seems to me that this simple if should resolve the problem described in gh-342
> gh-342: Rest Docs stubs with no body

- README.adoc
- docs/src/main/asciidoc/migrations.adoc
- docs/src/main/asciidoc/spring-cloud-contract.adoc
- docs/src/main/asciidoc/verifier/introduction.adoc
- spring-cloud-contract-stub-runner/README.adoc
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/HttpServerStub.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/NoOpHttpServerStub.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/StubRunner.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/StubRunnerExecutor.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/StubRunnerOptions.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/StubRunnerOptionsBuilder.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/StubServer.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/junit/StubRunnerRule.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/provider/wiremock/WireMockHttpServerStub.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/spring/AutoConfigureStubRunner.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/spring/StubRunnerConfiguration.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/spring/StubRunnerProperties.java
- spring-cloud-contract-stub-runner/src/test/groovy/org/springframework/cloud/contract/stubrunner/junit/StubRunnerRuleSpec.groovy
- spring-cloud-contract-stub-runner/src/test/groovy/org/springframework/cloud/contract/stubrunner/spring/StubRunnerConfigurationSpec.groovy
- tests/spring-cloud-contract-stub-runner-moco/src/test/groovy/org/springframework/cloud/contract/stubrunner/provider/moco/MocoHttpServerStub.groovy
without this feature we're missing an option to print all mappings registered for servers
with this feature it will be much easier to debug what was registered in which http server stub. The mappings will be dumped to files with name artifactName_registeredPort
fixes #355
> Adding option to dump mappings to files

- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/util/DelegatingJsonVerifiable.java
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/MethodBodyBuilderSpec.groovy
without this change when a contract contains a long value inside the body, then the code fails to compile since the provided number is assumed to be an integer.
with this change we're appending an `L` literal to that value for the compiler to assume that it's a long value.
> Tests fail to compile when the contract contains a long value

- README.adoc
- docs/src/main/asciidoc/verifier/contract.adoc
- docs/src/main/asciidoc/verifier/introduction.adoc
- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/Common.groovy
- spring-cloud-contract-stub-runner/README.adoc
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/StubRepository.java
- spring-cloud-contract-tools/spring-cloud-contract-converters/src/main/groovy/org/springframework/cloud/contract/verifier/wiremock/DslToWireMockConverter.groovy
- spring-cloud-contract-tools/spring-cloud-contract-converters/src/test/groovy/org/springframework/cloud/contract/verifier/wiremock/DslToWireMockClientConverterSpec.groovy
- spring-cloud-contract-tools/spring-cloud-contract-converters/src/test/groovy/org/springframework/cloud/contract/verifier/wiremock/WireMockToDslConverterSpec.groovy
- spring-cloud-contract-tools/spring-cloud-contract-converters/src/test/groovy/org/springframework/cloud/contract/verifier/wiremock/WiremockScenarioConverterSpec.groovy
- spring-cloud-contract-tools/spring-cloud-contract-maven-plugin/src/main/java/org/springframework/cloud/contract/maven/verifier/GenerateTestsMojo.java
- spring-cloud-contract-tools/spring-cloud-contract-spec-pact/src/test/groovy/org/springframework/cloud/contract/verifier/spec/pact/PactContractConverterSpec.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/file/ContractFileScanner.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/util/ContractVerifierDslConverter.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/SingleTestGeneratorSpec.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/util/ContractVerifierDslConverterSpec.groovy
- spring-cloud-contract-verifier/src/test/resources/classpath/readFromFile.groovy
- spring-cloud-contract-verifier/src/test/resources/classpath/request.json
- spring-cloud-contract-verifier/src/test/resources/classpath/response.json
- spring-cloud-contract-wiremock/src/test/java/org/springframework/cloud/contract/wiremock/restdocs/ContractDslSnippetTests.java
without this change large bodies can't be parsed by the compiler
with this change we allow those bodies to be read from files
fixes #357
> Added support for referencing file contents in the contract

- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/RegexPatterns.groovy
- spring-cloud-contract-spec/src/test/groovy/org/springframework/cloud/contract/spec/internal/RegexPatternsSpec.groovy
- spring-cloud-contract-tools/spring-cloud-contract-converters/src/test/groovy/org/springframework/cloud/contract/verifier/wiremock/DslToWireMockClientConverterSpec.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/JaxRsClientMethodBuilderSpec.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/MockMvcMethodBodyBuilderSpec.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/dsl/WireMockGroovyDslSpec.groovy
So that email addresses with .online on the end are valid.
> Support for generic top level domain .online in the email regular expression  

- spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockConfiguration.java
- spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/file/ResourcesFileSource.java
- spring-cloud-contract-wiremock/src/test/java/org/springframework/cloud/contract/wiremock/AutoConfigureWireMockStubsAndMultipleFilesApplicationTests.java
If specified subDirectoryName exists in more the one FileSource, return another instance of ResourcesFileSource containing all matched FileSources.
> Added composite child support.

- spring-cloud-contract-stub-runner/pom.xml
- tests/spring-cloud-contract-stub-runner-boot-eureka/pom.xml
Spring Cloud Netflix project renamed the starters adding `-netflix-` in
the artifactId. This commit fixes with the new artifacId.
> Update Netflix starters dependencies

- docs/src/main/asciidoc/verifier_contract.adoc
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/provider/wiremock/WireMockHttpServerStub.java
- spring-cloud-contract-stub-runner/src/test/groovy/org/springframework/cloud/contract/stubrunner/provider/wiremock/TestWireMockExtensions.groovy
- spring-cloud-contract-stub-runner/src/test/groovy/org/springframework/cloud/contract/stubrunner/provider/wiremock/WireMockHttpServerStubSpec.groovy
- spring-cloud-contract-stub-runner/src/test/resources/META-INF/spring.factories
- spring-cloud-contract-stub-runner/src/test/resources/transformers.json
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/dsl/wiremock/DefaultResponseTransformer.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/dsl/wiremock/WireMockExtensions.java
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/dsl/wiremock/WireMockResponseStubStrategy.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/dsl/WireMockGroovyDslSpec.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/dsl/wiremock/TestWireMockExtensions.groovy
- spring-cloud-contract-verifier/src/test/resources/META-INF/spring.factories
without this change we set only a single extension "response-transformer" without an option to provide any other ones
with this change we introduce the "spring.factories" based extension model. It's enough to provide your own implementation of `org.springframework.cloud.contract.verifier.dsl.wiremock.WireMockExtensions` and register it in `spring.factories`. That way you can control all extensions (request / response).
fixes #425
@Buzzardo could you please check out the docs I've added here?
@maverick1601 can you build this locally and check if this suits your needs?
> Introduced adding of custom WireMock extensions

- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/spring/StubRunnerProperties.java
Fixes a minor typo - order of version and classifier in javadoc.
> Fix the order of version and classifier

- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/MethodBodyBuilder.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/MethodBodyBuilderSpec.groovy
... so that the actual class of the object is returned instead of
potentially an element with key "class" if object is a Map.
fixed #509
> replaced ".class" with ".getClass()"

- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/Input.groovy
- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/OutputMessage.groovy
- spring-cloud-contract-spec/src/test/groovy/org/springframework/cloud/contract/spec/internal/ContractSpec.groovy
We found that we were unable to use pattern properties such as `anyAlphaUnicode()` in messaging contracts and were told to open a bug report. We believe these changes would resolve the issue.
> Support pattern properties in messaging contracts

- docker/spring-cloud-contract-docker/project/build.gradle
Because of Gradle's project lifecycle, disabling tasks in the script doesn't
work as expected, ./gradlew publish will still try to execute
:publishMavenJavaPublicationToMavenRepository and fail even if PUBLISH_ARTIFACTS
is set to false. To avoid that and make sure all publish tasks are disabled
script need to listen for tasks graph event to be ready and then disable the tasks.
> Fix disabling of publish task when env property is set

- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/PatternValueDslProperty.groovy
- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/RegexPatterns.groovy
- spring-cloud-contract-spec/src/test/groovy/org/springframework/cloud/contract/spec/internal/RegexPatternsSpec.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/converter/YamlContract.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/converter/YamlContractConverter.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/JaxRsClientMethodBuilderSpec.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/MockMvcMethodBodyBuilderSpec.groovy
Currently were copy and pasting a lot of regexes for doubles throughout our services and the corresponding contracts. Maybe having this could be helpful for others too. (Was super glad someone already added `anyIso8601WithOffset`)
A few sidenotes:
Since the change is a lot more invasive than I initially thought. Is there a suggested way to extend the functionality without changing the library? E.g. we use the type coordinate (lat, lng) quite a lot. But thats probably not generic enough to be added to spring-cloud-contract.
Would there be an interest in `anyHttpsUrl()` (current one only creates `http:`) and `anyPositiveNumber()` (looks weird to the stubrunner consumers if they get like `"pages": -472498` in a response.
> Added anyDouble DslProperty

- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/JUnitMessagingMethodBodyBuilder.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/MessagingMethodBodyBuilderSpec.groovy
+ Update tests to reflect desired behavior.
re: https://github.com/spring-cloud/spring-cloud-contract/issues/587
> Make headers matches in generated jUnit code escape regex '\'s.

- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/PatternValueDslProperty.groovy
- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/RegexPatterns.groovy
- spring-cloud-contract-spec/src/test/groovy/org/springframework/cloud/contract/spec/internal/RegexPatternsSpec.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/JaxRsClientMethodBuilderSpec.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/MessagingMethodBodyBuilderSpec.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/MockMvcMethodBodyBuilderSpec.groovy
As discussed in https://github.com/spring-cloud/spring-cloud-contract/pull/571
Feel free to offer feedback of any kind, e.g. i'm not sure if duplicating the "perfect URL validation regex" testcases is overkill.
On a sidenote:
shameless plug for https://github.com/marcingrzejszczak/jsonassert/issues/20 😁since it's affecting sprint-cloud-contract (I can fix it, if its considered a bug)
As always, thanks a bunch for the tool!
> Extend matchers

- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/JaxRsClientJUnitMethodBodyBuilder.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/JaxRsClientSpockMethodRequestProcessingBodyBuilder.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/RequestProcessingMethodBodyBuilder.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/JaxRsClientMethodBuilderSpec.groovy
Maybe this is behaviour more users would find helpful.
We had an issue with a failing build due to FindBugs running over the generated verifier tests (now added to the excluded packages).
In the case of `HEAD` the `responseAsString` was not used and FindBugs cried "unused variable" and failed.
Of course it could be improved upon. Something along the lines of ```IF assert on response THEN parse response```
But IMHO this would go against the spec for [HEAD](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD)
> Avoid body parsing for HEAD request

- docs/src/main/asciidoc/verifier_setup.adoc
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/StubRunnerOptions.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/junit/StubRunnerRuleOptions.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/spring/AutoConfigureStubRunner.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/spring/StubRunnerProperties.java
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/groovy/org/springframework/cloud/contract/verifier/plugin/ContractVerifierExtension.groovy
@marcingrzejszczak, I will start small:)
Do you think it can be useful? Otherwise it can be confusing because stubs jar will still be in the local repo even when Git is used.
> snapshotCheckSkip javadoc enhancement

- docs/src/main/asciidoc/verifier_contract.adoc
- spring-cloud-contract-tools/spring-cloud-contract-pact/src/main/groovy/org/springframework/cloud/contract/stubrunner/PactStubDownloaderBuilder.java
- spring-cloud-contract-tools/spring-cloud-contract-pact/src/test/groovy/org/springframework/cloud/contract/stubrunner/PactStubDownloaderBuilderSpec.groovy
Fallback to `contractsRepositoryUsername` and `contractsRepositoryPassword` (maven) or `contractRepository.username` and `contractRepository.password` (gradle) in case the pact broker options for the username and password are not set.
Closes #636
> Credential properties for pact broker

- spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/Contract.groovy
Ultra minor change.
The wording of `greater priority` led to an issue in a project where a contract with `priority(999)` (supposedly match first) and `priority(888)` (supposedly match second) was created. The example how `priority(1)` would match before `priority(2)` would have resolved this I guess :)
> Improve docs on contract priority

- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/file/ContractFileScanner.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/file/ContractFileScannerSpec.groovy
- spring-cloud-contract-verifier/src/test/resources/directory/with/custom/yml/custom.yml
Currently, the YamlContractConverter is used for any file that ends with .yaml or .yml. However, if I specify my custom converter for yaml files - like Swagger or OpenAPI or any other custom format - the YamlContractConverter is chosen as first option.
Whether or not it makes sense to write a custom converter for other yaml formats, Spring Cloud Contract should be flexible and extensible.
> Move YamlContractConverter list of available contract converters.

- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/JUnitMethodBodyBuilder.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/RestAssuredJUnitMethodBodyBuilder.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/SpockMethodRequestProcessingBodyBuilder.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/util/RegexpBuilders.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/MethodBodyBuilderSpec.groovy
When matching non-json or xml body with regex the expression gets
escaped. Because of that all standard patterns (number(), positiveInt())
will not work as well as any other regex involving escaped characters.
E.g.
`response {
status OK()
body(value(stub("1"), test(number())))
}`
Will generate invalid matcher:
`assertThat(responseBody).matches("-?(d*.d+|d+)");`
Valid version is:
`assertThat(responseBody).matches("-?(\\d*.\\d+|\\d+)");`
> Fix using regex patterns when matching raw body value

- pom.xml
- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/messaging/camel/CamelStubMessages.java
- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/messaging/camel/ContractVerifierCamelMessageBuilder.java
Spring Cloud Contract can not be used with new version of Camel due to usage of deprecated constructor of DefaultMessage, which as of now requires an instance of CamelContext.
> bump camel version

- docs/src/main/asciidoc/spring-cloud-wiremock.adoc
Sometimes people want to use methods like `addMockServiceRequestListener`, which are not static. But there is no any notes about  `WireMockServer` in spring-cloud-wiremock documentation. 
I saw how the developers did not know about it and made a mistake. 
They mixed junit4 and junit5 even for new services, because `WireMockRule` inherits from `WireMockServer` and  provides non static methods.
This situation may seem funny, but many can get into it.
> Improved spring-cloud-wiremock documentation

- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/messaging/StubRunnerStreamsIntegrationAutoConfiguration.java
Do reference to issue: #803
I have cheched it and it works using `@SpringBootApplication( exclude = { TestSupportBinderAutoConfiguration.class })`
> fix stub runner application when is in real stream mode

- spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockConfiguration.java
When port = 0, WireMock will assign different ports for admin server and mock server. As a result, the original implementation will send admin HTTP requests to mock server, which is wrong behavior.
If this PR got merged, WireMock will directly add stubs via internal Java interface instead of sending admin HTTP requests, which is correct behavior and also improves performance.
> Configure for WireMockServer instead of port

- 1.0.x/ghpages.sh
- 1.1.x/ghpages.sh
- 1.2.x/ghpages.sh
- 2.0.x/ghpages.sh
- ghpages.sh
This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
* http://stackoverflow.com/questions/1593051/how-to-programmatically-determine-the-current-checked-out-git-branch with 5 occurrences migrated to:  
https://stackoverflow.com/questions/1593051/how-to-programmatically-determine-the-current-checked-out-git-branch ([https](https://stackoverflow.com/questions/1593051/how-to-programmatically-determine-the-current-checked-out-git-branch) result 200).
* http://stackoverflow.com/questions/29300806/a-bash-script-to-check-if-a-string-is-present-in-a-com …
> URL Cleanup

- docs/src/main/asciidoc/verifier_setup.adoc
It looks somehow odd with mixed tabs and spaces:
> Fix formatting in documentation

- docker/spring-cloud-contract-docker/project/build.gradle
- docs/src/main/asciidoc/verifier_setup.adoc
Since there was no way to download contracts from external binary repository as authenticated user while using Docker Verifier image, it was added.
> Docker image support for authenticated contracts download

- spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockApplicationListener.java
- spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockConfiguration.java
This is to avoid the httpsPortDynamic being set to true on the context initialisation, but then being updated to false when the context is refreshed.
Fix for #1028
> #1028: Register port now only handles auto port values.

- spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockApplicationListener.java
- spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockConfiguration.java
PR contains the following fixes.
1) Register port now only handles auto port values - Fix for #1028.
2) Register only sets the ports when the values are available in the environment configuration - this resolves the issue seen in the contract-car-rental project/RentACarTests tests.
No test case available. Ideally, we would add a similar test as the RentACarTests to the spring-cloud-contract-stub-runner project. However, this doesn't seem to be running all tests in that project.
> #883/#1028.: Further DirtiesContext fix where the context is refreshed during the test phase

- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/build.gradle
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/gradle/release.gradle
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/resources/META-INF/gradle-plugins/org.springframework.cloud.contract.properties
This PR makes possible to apply the Spring Cloud Contract Gradle plugin with short syntax (as requested in #629):
```
plugins {
id 'org.springframework.cloud.contract' version 'XXX.RELEASE'
}
```
**Please note**. This change keeps backward compatibility with 2.x.
The feature is achieved by:
1. Adding an alias for the Gradle plugin id - making it compatible with Plugin portal requirements.
2. Configuring effecting publishing to Plugin portal with a dedicated plugin.
1. Valid `gradle.publish.key` and `gradle.publish.secret` properties have to be added in CI/CD configuration (e.g. in `~/.gradle/gradle.properties`.
2. The CI/CD server should call `publishPlugins` (directly or that task can be - after testing - made a requirement for the general release task).
1. This solution keeps backward …
> Deploy also to Gradle plugin portal (#629)

- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/dsl/wiremock/WireMockXmlStubStrategySpec.groovy
Repair test execution failure caused by different operating system newline characters(mac or windows).
Windows newline character is "\r\n".
UNIX newline character is "\n".
MAC newline character is "\r".
> Repair test execution failure in windows or mac system.

- docker/spring-cloud-contract-docker/project/build.gradle
- docs/src/main/asciidoc/verifier_setup.adoc
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/groovy/org/springframework/cloud/contract/verifier/plugin/SpringCloudContractVerifierGradlePlugin.groovy
Adds the possibility to provide custom stubs classifier. Might be useful to serve as some kind of tag for the stubs published.
This PR also deals with the issue that I stumbled upon initially with SCC Gradle plugin not applying the `stubsSuffix` property set in `build.gradle`. It always used the default value instead, because the stubs jar task was created before the project was evaluated.
> WIP: Docker verifier support for custom producer stubs classifier

- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/AetherStubDownloader.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/CompositeStubDownloaderBuilder.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/StubRunnerOptions.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/StubRunnerOptionsBuilder.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/junit/StubRunnerExtension.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/junit/StubRunnerExtensionOptions.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/junit/StubRunnerRule.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/junit/StubRunnerRuleOptions.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/spring/AutoConfigureStubRunner.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/spring/StubRunnerProperties.java
- spring-cloud-contract-stub-runner/src/test/groovy/org/springframework/cloud/contract/stubrunner/AetherStubDownloaderSpec.groovy
- spring-cloud-contract-stub-runner/src/test/groovy/org/springframework/cloud/contract/stubrunner/StubRunnerOptionsBuilderSpec.groovy
- spring-cloud-contract-stub-runner/src/test/java/org/springframework/cloud/contract/stubrunner/CompositeStubDownloaderBuilderTests.java
- spring-cloud-contract-stub-runner/src/test/java/org/springframework/cloud/contract/stubrunner/StubDownloaderBuilderProviderTests.java
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/groovy/org/springframework/cloud/contract/verifier/plugin/ContractVerifierExtension.groovy
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/groovy/org/springframework/cloud/contract/verifier/plugin/GradleContractsDownloader.groovy
- spring-cloud-contract-tools/spring-cloud-contract-maven-plugin/src/main/java/org/springframework/cloud/contract/maven/verifier/ConvertMojo.java
- spring-cloud-contract-tools/spring-cloud-contract-maven-plugin/src/main/java/org/springframework/cloud/contract/maven/verifier/GenerateTestsMojo.java
- spring-cloud-contract-tools/spring-cloud-contract-maven-plugin/src/main/java/org/springframework/cloud/contract/maven/verifier/MavenContractsDownloader.java
- tests/spring-cloud-contract-stub-runner-context-path/src/test/java/com/example/loan/FailFastLoanApplicationServiceTests.java
without this change we throw an exception if no stubs / contracts were found
with this change we catch exceptions from aether stub downloader and if there are no stubs found whatsover, and a switch is set to fail in that case, then we do throw an exception that no stubs / contracts were found
fixes gh-895
> Add a switch to fail on no stubs

- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/groovy/org/springframework/cloud/contract/verifier/plugin/ContractsCopyTask.groovy
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/groovy/org/springframework/cloud/contract/verifier/plugin/GenerateServerTestsTask.groovy
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/groovy/org/springframework/cloud/contract/verifier/plugin/InitContractsTask.groovy
With current implementation of the `GradleContractsDownloader`, where
we have custom caching, `InitContractsTask` doesn't really need to be
incremental. Moreover, there is an issue in current implementation of
the `InitContractsTask`: it doesn't mark itself as out of date when
dynamic dependency is used (`+` or `SNAPSHOT` version). So for now just
disabling incremental build for that task.
Also restored old behaviour, where we used to always use `".*"` pattern
to define included contracts for `GenerateServerTests` task.
Also fixed minor logging issue.
Fixes gh-1133
> Disable broken incremental build for InitContractsTask

- docker/spring-cloud-contract-docker/project/build.gradle
Originally, SCC Verifier Docker published artifacts twice.
Once defined in build.gradle - which also uploaded the original contracts and second time in a publish stubs task defined in gradle plugin. This PR removes the definition from build.gradle and now only the stubs are published and just once.
> SCC Verifier Docker now publishes stubs just once

- docs/src/main/asciidoc/getting-started.adoc
The links to the http-server and http-client samples were pointing to a url with an unresolved `{branch}` attribute.
Replace the links by instead using the attributes `{samples_code}` and `{standalone_samples_path}`.
See the 2 broken links under https://cloud.spring.io/spring-cloud-contract/reference/html/getting-started.html#getting-started-cdc
> Fix links to http-server and http-client samples in doc

- spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/restdocs/WireMockSnippet.java
- spring-cloud-contract-wiremock/src/test/java/org/springframework/cloud/contract/wiremock/restdocs/WireMockSnippetTests.java
In WireMockSnippet requestPattern is generated by urlEqualTo method. In order to working properly with queryParameters it should be urlPathEqualTo method. Please see the example below:
Generated currently by WireMockSnippet
```
{
"id" : "3a08a940-3efa-4086-aaf2-fd3718e23bd5",
"request" : {
"url" : "/test",
"method" : "GET",
"queryParameters" : {
"userId" : {
"equalTo" : "11"
}
}
},
"response" : {
"status" : 200,
"body" : "{}" 
},
"uuid" : "3a08a940-3efa-4086-aaf2-fd3718e23bd5"
}
```
Request was not matched:
```
curl  'http://localhost:8080/test?userId=11'
Request was not matched
=======================
-----------------------------------------------------------------------------------------------------------------------
| Closest stub                                             | Request …
```
> Added support of query parameters for RestDocs for WireMock stubs

- docker/spring-cloud-contract-docker/project/build.gradle
- docs/src/main/asciidoc/docker-project.adoc
New option for publishing stubs just into local .m2 added.
Fixes #1283
> Verifier Docker image PUBLISH_ARTIFACTS_OFFLINE option

- docker/spring-cloud-contract-docker/project/build.gradle
- docker/spring-cloud-contract-docker/project/build.sh
- docs/src/main/asciidoc/docker-project.adoc
While the previous approach did publish the contracts to local .m2 repository, it did not create the maven-metadata-local.xml file indicating a local release. It instead created maven-metadata.xml, which indicates a remote release. This wasn't issue when the stubs were retrieved by Gradle directly (in our flow we pre-check availability of these stubs by Gradle), it did however cause problems when they were being resolved by AetherStubDownloader used in SCC Stub Runner.
In addition, this newer implementation allows to enable any publish (remote or local) independently of each other, which wasn't the case previously.
Fixes #1283 - again
> Local stub publishing reimplemented

- docs/src/main/asciidoc/_project-features-wiremock.adoc
- docs/src/main/asciidoc/howto.adoc
Reverts spring-cloud/spring-cloud-contract#1293
> Revert "Corrected links to use samples_branch rather than branch in documentation."

- specs/spring-cloud-contract-spec-java/src/main/java/org/springframework/cloud/contract/spec/internal/OutputMessage.java
BodyMatchers should not be deprecated because they replaced testMatchers and according to the documentation it is the current way of verifying.
> Remove deprecated and fix wrong javadoc on bodyMatchers - they replaced testMatchers and are not deprecated

- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/JUnit4IgnoreMethodAnnotation.java
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/JUnit5IgnoreMethodAnnotation.java
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/SpockIgnoreMethodAnnotation.java
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/SingleTestGeneratorSpec.groovy
- JUnit, JUnit5, Spock *IgnoreMethodAnnotation refactored (TestNG is not affected)
- extended more tests to cover possible scenarios for diff frameworks
- added tests for JUnit, JUnit5, TestNG, Spock for **ignore** (combinations of DSL and config) processing and verification
- by applying fixed spring-cloud-verifier artifact in local project
> Fixed issues with ignored() contract-DSL for Junit, JUnit5 and Spock #1346

- docs/src/main/asciidoc/howto.adoc
Very simple spelling change I noticed while going through the documentation.
> Fixed spelling error in howto

- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/util/xml/XmlToXPathsConverter.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/util/xml/XmlToXPathsConverterSpec.groovy
This PR adds test to validate the expected behavior of the XmlToXPathConverter class when the input is an xml that contains an name space and one that does not contain such namespace.
The implementation of the fix consists in enabling the name space aware property of the DocumentBuilderFactory so that the document instance created from the xml is capable of identify the attributes prefixes and use the DOMNamespaceContect to translate the identified name spaces to the required dom elements.
> bug: handle xml with namespaces closes #1427

- docs/src/main/asciidoc/_attributes.adoc
- docs/src/main/asciidoc/_project-features-contract.adoc
- docs/src/main/asciidoc/advanced.adoc
- docs/src/test/resources/contract.yml
- samples/standalone/dsl/http-client/src/main/java/com/example/loan/LoanApplicationService.java
- samples/standalone/dsl/http-client/src/test/java/com/example/loan/LoanApplicationServiceTests.java
- samples/standalone/dsl/http-server/src/test/resources/contracts/fraud/shouldReturnFraudStats.groovy
- samples/standalone/dsl/http-server/src/test/resources/contracts/yml/fraud/shouldReturnFraudStats.yml
- specs/spring-cloud-contract-spec-java/src/main/java/org/springframework/cloud/contract/spec/Contract.java
- specs/spring-cloud-contract-spec-kotlin/src/main/kotlin/org/springframework/cloud/contract/spec/ContractDsl.kt
- specs/spring-cloud-contract-spec-kotlin/src/test/kotlin/org/springframework/cloud/contract/spec/ContractTests.kt
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/StubRunnerExecutor.java
- spring-cloud-contract-tools/spring-cloud-contract-converters/src/main/java/org/springframework/cloud/contract/verifier/converter/StubGenerator.java
- spring-cloud-contract-tools/spring-cloud-contract-converters/src/main/java/org/springframework/cloud/contract/verifier/converter/StubPostProcessor.java
- spring-cloud-contract-tools/spring-cloud-contract-converters/src/main/java/org/springframework/cloud/contract/verifier/wiremock/DefaultWireMockStubPostProcessor.java
- spring-cloud-contract-tools/spring-cloud-contract-converters/src/main/java/org/springframework/cloud/contract/verifier/wiremock/DslToWireMockClientConverter.java
- spring-cloud-contract-tools/spring-cloud-contract-converters/src/main/java/org/springframework/cloud/contract/verifier/wiremock/DslToWireMockConverter.java
- spring-cloud-contract-tools/spring-cloud-contract-converters/src/main/java/org/springframework/cloud/contract/verifier/wiremock/WireMockStubPostProcessor.java
- spring-cloud-contract-tools/spring-cloud-contract-converters/src/test/java/org/springframework/cloud/contract/verifier/wiremock/DefaultWireMockStubPostProcessorTests.java
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/converter/ContractsToYaml.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/converter/YamlContract.java
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/converter/YamlToContracts.groovy
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/dsl/wiremock/WireMockStubStrategy.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/converter/YamlContractConverterSpec.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/dsl/wiremock/WireMockGroovyDslSpec.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/dsl/wiremock/WireMockStubVerifier.groovy
- spring-cloud-contract-verifier/src/test/resources/contractsToCompile/contract_rest_with_tags.java
fixes #1340 
* you can add the following entry in the `wiremock` metadata map
```groovy
Contract.make {
request {
method GET()
url '/drunks'
}
response {
status OK()
body([
count: 100
])
headers {
contentType("application/json")
}
}
metadata([wiremock: '''\
{
"response" : {
"delayDistribution": {
"type": "lognormal",
"median": 80,
"sigma": 0.4
}
}
}
'''
])
```
fixes #1078 , #1406 
* you can add the following entry in the `wiremock` metadata map (unfortunately webhooks won't work due to a mismatch of versions between WireMock 2.21 (used by extension) and 2.27 (used by Spring Cloud Contract).
```groovy
Contract.make {
request {
method GET()
url '/drunks'
}
response {
status OK()
body([
count: 100
])
headers {
contentType("application/json")
}
}
metadata([wiremock: '''\
{
"postServeActions" …
```
> Adds metadata to contracts

- docs/src/main/asciidoc/gradle-project.adoc
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/groovy/org/springframework/cloud/contract/verifier/plugin/ContractVerifierExtension.java
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/groovy/org/springframework/cloud/contract/verifier/plugin/SpringCloudContractVerifierGradlePlugin.groovy
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/test/groovy/org/springframework/cloud/contract/verifier/plugin/ContractVerifierSpec.groovy
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/test/resources/functionalTest/scenarioProject/build.gradle
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/test/resources/functionalTest/scenarioProjectKotlin/build.gradle.kts
> Disable stubsJar publication by default.

- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/messaging/amqp/RabbitMockConnectionFactoryAutoConfiguration.java
- spring-cloud-contract-verifier/src/test/java/org/springframework/cloud/contract/verifier/messaging/amqp/ContractVerifierAmqpAutoConfigurationTests.java
Autoconfigure a barebones ConnectionFactory implementation instead of CachingConnectionFactory. CachingConnectionFactory would require additional mocking to support its transaction tracking and caching the mocked connection isn't necessary.
Fixes gh-1259
> Autoconfigure a basic ConnectionFactory as RabbitMockConnectionFactory

- docs/pom.xml
- docs/src/main/asciidoc/_project-features-flows.adoc
- docs/src/main/asciidoc/_project-features-stubrunner.adoc
- docs/src/main/asciidoc/documentation-overview.adoc
- docs/src/main/asciidoc/project-features.adoc
- docs/src/main/java/org/springframework/cloud/contract/docs/Main.java
- docs/src/test/java/org/springframework/cloud/contract/docs/AdditionalResourcesGenerationTests.java
- pom.xml
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/provider/wiremock/WireMockHttpServerStub.java
- spring-cloud-contract-tools/spring-cloud-contract-converters/src/test/groovy/org/springframework/cloud/contract/verifier/wiremock/DslToWireMockClientConverterSpec.groovy
- spring-cloud-contract-verifier/pom.xml
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/dsl/wiremock/WireMockRequestStubStrategy.groovy
- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/dsl/ContractVerifierMetadata.java
- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/dsl/wiremock/SpringCloudContractRequestMatcher.java
- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/dsl/wiremock/WireMockResponseStubStrategy.java
- spring-cloud-contract-verifier/src/test/java/org/springframework/cloud/contract/verifier/dsl/ContractVerifierMetadataTests.java
- spring-cloud-contract-verifier/src/test/java/org/springframework/cloud/contract/verifier/dsl/wiremock/GraphQLRequestMatcherTests.java
- spring-cloud-contract-verifier/src/test/java/org/springframework/cloud/contract/verifier/dsl/wiremock/SpringCloudContractRequestMatcherTests.java
fixes #670 
adding @Buzzardo in cc since there are docs changes
> Added GraphQL support

- samples/standalone/webclient/http-server/build.gradle
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/ContractsCopyTask.java
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/GenerateClientStubsFromDslTask.java
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/GenerateServerTestsTask.java
When the `contractsDslDir` doesn't exist the tasks would fail. By using `@SkipWhenEmpty` Gradle won't throw an error when the `contractsDslDir` doesn't exist.
> Skip tasks when input directory is empty

- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/StubRunnerFactory.java
When running on windows and downloading stubs from remote repository, the stub runner fails with the below exception. This is due to passing the file path of the unpacked stub to `ResourceResolver.resource(String url)`. On windows, this will be something like `C:\...` rather than the corresponding URL `file:C:/...` that the underlying [ResourceLoader.getResource(String url)](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/io/ResourceLoader.html#getResource-java.lang.String-) expects
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'batchStubRunnerBeanPostProcessor' defined in org.springframework.cloud.contract.stubrunner.spring.StubRunnerConfiguration: Unsatisfied dependency expressed through …
```
> Fix invalid resource url on windows

- docs/src/main/asciidoc/_additional-stubrunner-configprops.adoc
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/GitRepo.java
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/ScmStubDownloaderBuilder.java
- spring-cloud-contract-stub-runner/src/test/java/org/springframework/cloud/contract/stubrunner/GitRepoTests.java
Added stubrunner.properties.git.ensure-git-suffix to disable the automatic
addition of '.git' to git URLs.  This adds support for repositories which
don't support these kind of URLs (for example Azure DevOps).
As discussed in https://gitter.im/spring-cloud/spring-cloud-contract?at=5f97e00f631a250ab295bdb0
> Option to disable '.git' suffix in git URLs

- docs/src/main/asciidoc/_project-features-contract.adoc
- docs/src/main/asciidoc/gradle-project.adoc
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/build.gradle
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/ContractVerifierExtension.java
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/ContractsCopyTask.java
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/SpringCloudContractVerifierGradlePlugin.java
This continues the effort started in PR #1480 and as discussed there, it was determined that a separate PR should be opened to handle the changed needed for the Maven plugin as well.
> Migrate DSL contracts to 'contractTest' source set

- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/JsonBodyVerificationBuilder.java
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/util/JsonToJsonPathsConverter.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/SpringTestMethodBodyBuildersSpec.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/YamlMockMvcMethodBodyBuilderSpec.groovy
Fixes gh-1423
This change allows the response body to be either an empty map (`{}`) or empty collection (`[]`). They can be represented as follows *(yaml and groovy dsl, respectively):*
**empty collection**
```yaml
body: []
```
```groovy
body([])
```
**empty map**
```yaml
body: {}
```
```groovy
body({})
```
---
The report of the NPE occurs when handling a single null element collection:
```yaml
body:
- 
```
```groovy
body([null])
```
At first I was going to fix both w/in this code proposal but it became evident that it should it be its own solve - I created #1557 .
> Adds handling for empty list and empty map response body

- spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockTestExecutionListener.java
- spring-cloud-contract-wiremock/src/test/java/org/springframework/cloud/contract/wiremock/MetaAnnotationWithResetAfterEachTestApplicationTests.java
With this change, the stubbing of WireMock will be reset even if only a
meta-annotation is annotated with `@AutoConfigureWireMock`.
Fixes gh-1204
> Support auto configuration on meta-annotations

- spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/AutoConfigureWireMock.java
- spring-cloud-contract-wiremock/src/test/java/org/springframework/cloud/contract/wiremock/AutoConfigureWireMockConfigurationInYamlTests.java
- spring-cloud-contract-wiremock/src/test/resources/application-customfoo.yml
- spring-cloud-contract-wiremock/src/test/resources/custom-from-yml/__files/hello-custom.json
- spring-cloud-contract-wiremock/src/test/resources/custom-from-yml/mappings/custom-test-endpoint.json
Allows @AutoConfigureWireMock to respect user-specified properties in application.yml
Fixes gh-1555
> Allows @AutoConfigureWireMock to respect user-specified properties 

- samples/standalone/dsl/http-client/build.gradle
- samples/standalone/dsl/http-client/settings.gradle
- samples/standalone/dsl/http-server/build.gradle
- samples/standalone/dsl/http-server/settings.gradle
- samples/standalone/restdocs/http-server/build.gradle
- samples/standalone/restdocs/http-server/pom.xml
- samples/standalone/restdocs/http-server/settings.gradle
- samples/standalone/restdocs/http-server/src/test/java/com/example/fraud/StubGeneratorTests.java
- samples/standalone/webclient/http-client/build.gradle
- samples/standalone/webclient/http-client/settings.gradle
- samples/standalone/webclient/http-server/build.gradle
- samples/standalone/webclient/http-server/pom.xml
- samples/standalone/webclient/http-server/settings.gradle
- scripts/gradleOnly.sh
- spring-cloud-contract-tools/spring-cloud-contract-converters/src/main/java/org/springframework/cloud/contract/verifier/converter/RecursiveFilesConverterApplication.java
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/build.gradle
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/gradle/release.gradle
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/pom.xml
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/ContractsCopyTask.java
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/GenerateClientStubsFromDslTask.java
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/GenerateServerTestsTask.java
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/SpringCloudContractVerifierGradlePlugin.java
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/VersionExtractor.java
- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/TestGeneratorApplication.java
- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/converter/ToYamlConverterApplication.java
This addresses the broken Kotlin support by keeping all things sc-contract in a totally isolated classloader (via process forking). This is the same pattern employed by the Kotlin plugin when attempting to perform Kotlin compilation (albeit much easier in our case).
> Attempt to keep Kotlin totally off the classpath

- spring-cloud-contract-dependencies/pom.xml
- spring-cloud-contract-starters/spring-cloud-starter-contract-verifier/pom.xml
- spring-cloud-contract-tools/spring-cloud-contract-maven-plugin/src/test/projects/complex-configuration/pom.xml
- spring-cloud-contract-tools/spring-cloud-contract-maven-plugin/src/test/projects/different-module-configuration/module/pom.xml
- spring-cloud-contract-verifier/pom.xml
The exclusions were added in gh-1568 in an effort to get rid of the old asm lib that jsonpath brings with it. However, it turns out the issue is bigger than that. Spring Cloud Contract has a direct dependency on `cglib:3.2.9` which in turn brings in a more recent `asm:7.x`. So even before the exclusions, the old `asm` lib was being cancelled out in favor of the new `asm` lib. I originally thought that the more recent asm was being brought in by `spring-core` but it actually shades `cglib` and `asm`. 
While the changes made in gh-1568 were probably harmless - they were not really providing any benefit. Let's remove the changes and revisit later and see if we can remove the direct dependence on cglib at that time as well. 
Reverts gh-1568
> Removes the exclusions of old asm lib from jsonpath lib.

- docs/src/main/asciidoc/_project-features-wiremock.adoc
Adds info note in Wiremock docs around use of WireMock.resetToDefaultMappings when using '_stubs' property.
Fixes gh-1451
> Adds info note in Wiremock docs around use of WireMock.resetToDefaultMappings

- spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/AutoConfigureWireMock.java
Having basic details added to javadoc makes it easy for other developers to find these details easily. Of course javadoc is in no way meant to be replacement for detailed documentation where this information is already available.
This PR is submitted in response to the discussion in thread #1583
> Add javadoc for AutoConfigureWireMock

- docs/src/main/asciidoc/_project-features-contract.adoc
- spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/util/xml/XmlToXPathsConverter.groovy
- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/util/xml/ArrayValueAssertion.java
- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/util/xml/XmlAsserter.java
- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/util/xml/XmlVerifiable.java
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/XmlMethodBodyBuilderSpec.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/util/xml/XmlToXPathsConverterSpec.groovy
- spring-cloud-contract-verifier/src/test/java/org/springframework/cloud/contract/verifier/util/ContractVerifierUtilTest.java
Adds support for unqualified namespaced XML content and fixes how qualified namespace URIs values are retrieved.
Fixes gh-1571 gh-1517
-----
The main theme behind this change is to access XPath expressions for nodes that are using an unqualified namespace. Please read the document updates first as that should clarify a bit more.
This is definitely a problem of edge-casing and one could probably come up w/ a twisted nested complicated XML document that we may not properly support. I added in a decent set of complicated XML content in the tests but I also don't want to over complicate the maintenance of our tests. We can add more later if need be but we are definitely in a better position, code coverage wise, with the new additions in this code proposal.
----
I want to point the verbose …
> Adds support for unqualified namespaced XML content

- specs/spring-cloud-contract-spec-java/src/main/java/org/springframework/cloud/contract/spec/internal/PatternValueDslProperty.java
The current implementation of `anyOf()` always only selects the first value
when generating a property. It means that other possible enum values are always
ignored when producing a value for the property.
This changes the behaviour so that the value is picked at random from any of
the provided values. It could be considered a breaking changes because of the
change of behaviour although it shouldn't be from the contract perspective.
Fixes #1424
> Select value of an `anyOf()` property at random

- spring-cloud-contract-tools/spring-cloud-contract-converters/src/main/java/org/springframework/cloud/contract/verifier/wiremock/DefaultWireMockStubPostProcessor.java
Creating a contract like this:
```
Contract.make {            
metadata(
wiremock: [
stubMapping: [
metadata: [
foo: "bar"
]
]
]
)
}
}
```
will throw a `NullPointerException`:
```
Exception in thread "main" org.springframework.cloud.contract.verifier.converter.ConversionContractVerifierException: Unable to make conversion of client.groovy
at org.springframework.cloud.contract.verifier.converter.RecursiveFilesConverter.processFiles(RecursiveFilesConverter.java:145)
at org.springframework.cloud.contract.verifier.converter.RecursiveFilesConverterApplication.main(RecursiveFilesConverterApplication.java:43)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.size()" because "m" is null
at java.base/java.util.HashMap.putMapEntries(HashMap.java:497)
at …
```
> Fixed DefaultWireMockStubPostProcessor.setMetadata bug

- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/ContractsCopyTask.java
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/GenerateClientStubsFromDslTask.java
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/GenerateServerTestsTask.java
Relates to gh-1600.
As you can see in the changes, if `javaexec` were to exit with a return code of 1 an exception was raised and the stdout/stderr that we may have collected during debug logging would have been lost. By usage of the `finally` block we can now ensure that the stdout/stderr from the different forked processes we will create can be captured for debugging information.
> Ensure stdout/stderr are logged when using debug mode logging.

- README.adoc
- docs/src/main/asciidoc/_project-features-messaging.adoc
- spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/messaging/kafka/StubRunnerKafkaRouter.java
- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/messaging/kafka/ContractVerifierKafkaStubMessagesInitializer.java
- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/messaging/kafka/KafkaStubMessages.java
- tests/spring-cloud-contract-stub-runner-kafka/src/test/groovy/org/springframework/cloud/contract/stubrunner/messaging/kafka/KafkaStubRunnerSpec.groovy
- tests/spring-cloud-contract-stub-runner-kafka/src/test/resources/application.yml
- tests/spring-cloud-contract-stub-runner-kafka/src/test/resources/stubs/bookReturned3.groovy
Allows Kafka message keys to be used in messaging contract.
Fixes gh-1267
@marcingrzejszczak 
1. I struggled to find the proper place to add tests for this - please advise. I have been verifying it manually in the [producer_kafka](https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/master/producer_kafka) and [consumer_kafka](https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/master/consumer_kafka) sample projects. The sort of tests that are valuable here are integration tests (similar to what I am doing manually in the sample projects).
2. I would also like to add some docs around the configuration nuances of the key/value serdes. I will look for a good location to add this info in the current docs shortly. 
3. What is the process of the …
> Adds support for Kafka message keys in contracts

- specs/spring-cloud-contract-spec-java/src/main/java/org/springframework/cloud/contract/spec/internal/RegexPatterns.java
- spring-cloud-contract-tools/spring-cloud-contract-converters/src/test/groovy/org/springframework/cloud/contract/verifier/wiremock/DslToWireMockClientConverterSpec.groovy
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/dsl/wiremock/WireMockGroovyDslSpec.groovy
This fix remove required `\1` in boundary name. May be related to #1411
We can read in RFC (https://tools.ietf.org/html/rfc2046#section-5.1.1)
```
The only mandatory global parameter for the "multipart" media type is
the boundary parameter, which consists of 1 to 70 characters from a
set of characters known to be very robust through mail gateways, and
NOT ending with white space.
boundary := 0*69<bchars> bcharsnospace
bchars := bcharsnospace / " "
bcharsnospace := DIGIT / ALPHA / "'" / "(" / ")" /
"+" / "_" / "," / "-" / "." /
"/" / ":" / "=" / "?"
```
> Fix multipart request regex pattern

- docs/src/main/asciidoc/_project-features-contract.adoc
- docs/src/main/asciidoc/gradle-project.adoc
Fixes gh-1600
This is achieved by adding to the documentation that states that `kotlin-scripting-compiler-embeddable` needs to be added to your `build.gradle` in order to keep the Kotlin version used in the project in sync with that used to generate tests from the Kotlin DSL. As we have seen in gh-1600, the Kotlin runtime is sensitive to version discrepancies across modules down to the patch version. 
Additionally, noticed a broken link and some outdated Gradle configuration with respect to Rest Assured configuration, so I have corrected those as well.
> Add kotlin-scripting-compiler-embeddable for Kotlin DSL

- README.adoc
The following command, suggested by the README
```
git clone -c core.longPaths true https://github.com/spring-cloud/spring-cloud-contract.git
```
fails because Git recognizes `true` as the repo to be cloned.
Add equal sign (`=`) to fix this issue. This way Git will properly recognize `true` as the value for `core.longPaths`
> Fix Clone on Windows instructions

- docs/src/main/asciidoc/maven-project.adoc
Fixing typo on contractsProperties and adding a use case sample
> Fixing typo on contractsProperties

- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/messaging/kafka/ContractVerifierKafkaConfiguration.java
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/messaging/kafka/ContractVerifierKafkaHelperSpec.groovy
Fixes gh-1587
| ℹ️ I took the simple route of assuming UTF-8 and doing the conversion if its a byte[]. This fixes the issue at hand. |
| --- |
> Add support for comparing byte[] Kafka message header values

- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/messaging/kafka/ContractVerifierKafkaConfiguration.java
Fixes gh-1628
@marcingrzejszczak 
Basically, the `Collectors.toMap` does not handle null values. LAME
> Handle null kafka header values

- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/ContractsCopyTask.java
Fixes gh-1636
Using [spring-cloud-samples/spring-cloud-contract-samples - 3.0.x](https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/3.0.x) `producer` sample, I was able to recreate the issue described in gh-1636.
| Gradle Version | SCC Verifier Version | Result |
| ---------------- | ---------------------- | ------ |
| 5.6.4 | 3.0.2-SNAPSHOT | ✅ |
| 5.6.4 | 3.0.3-SNAPSHOT (local remove `@Internal`) | ✅ |
| 6.8.3 | 3.0.2-SNAPSHOT | ✅ |
| 6.8.3 | 3.0.3-SNAPSHOT (local remove `@Internal`) | ✅ |
| 7.0 | 3.0.2-SNAPSHOT | ❌ |
| 7.0 | 3.0.3-SNAPSHOT (local remove `@Internal`) | ✅ |
> Remove <at>Internal annotation

- docker/spring-cloud-contract-docker/Dockerfile
- docker/spring-cloud-contract-stub-runner-docker/Dockerfile
As part of 4d71108 Docker base images were updated to ubuntu:21.04. According to #1579 the intention is to update to Ubuntu LTS version. 21.04 is not LTS version and as a matter of fact it is not yet released version.
Change the docker base image to the the intended version 20.04 LTS.
> Fix Docker base image version

- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/builder/JaxRsUrlPathWhen.java
- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/builder/MockMvcQueryParamsWhen.java
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/MethodBodyBuilderSpec.groovy
Fixes gh-854. Query param isn't quoted if it's an ExecutionProperty, similarly to https://github.com/spring-cloud/spring-cloud-contract/blob/c323e3e105810498a2bb9869d87eb144d5c8d0d5/spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/builder/JaxRsRequestHeadersWhen.java#L46-L67
> Parse ExecutionProperty in queryParameters

- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/SpringCloudContractVerifierGradlePlugin.java
With Gradle 7.0, a new warning is being logged indicating that Gradle is using a fallback mode to ensure task correctness.
```
Execution optimizations have been disabled for task ':processContractTestResources' to ensure correctness due to the following reasons:
- Gradle detected a problem with the following location: '/home/runner/work/spring-cloud-contract-samples/spring-cloud-contract-samples/producer/build/generated-test-resources/contractTest'. Reason: Task ':processContractTestResources' uses this output of task ':generateContractTests' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#implicit_dependen …
```
> Add explicit dependency to generateContractTests task for processContractTestResources

- specs/spring-cloud-contract-spec-java/src/main/java/org/springframework/cloud/contract/spec/internal/RegexPatterns.java
- specs/spring-cloud-contract-spec/src/test/groovy/org/springframework/cloud/contract/spec/internal/RegexPatternsSpec.groovy
As some web services expect to receive a valid UUIDv4, rather than a rough UUID
pattern, we should provide a convenience method to generate them.
We should add test coverage to make it clear that this is a strict UUIDv4.
Also, allow uppercase UUID generation, as it's perfectly valid for a UUID to be
formatted with uppercase or lowercase, as per RFC4122 Section 3.
> Add support for v4 UUIDs, and allow UUIDs to be case insensitive

- docker/spring-cloud-contract-docker/Dockerfile
- docker/spring-cloud-contract-docker/project/README.adoc
- docker/spring-cloud-contract-stub-runner-docker/Dockerfile
- docs/src/main/asciidoc/docker-project.adoc
- added documentation on how to overwrite `build.gradle` with docker
- using the directories in docker container that are defined and described in the documentation and pre-create them with appropriate permissions during container image creation:
`/contracts`, `/spring-cloud-contract`, `/spring-cloud-contract-output`
> Fixes #1672: allow users to specify a custom build.gradle when using standalone docker image

- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/build.gradle
- spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/pom.xml
Minimal changes to get JGit working.
@marcingrzejszczak, I'm not sure if there was a purpose for which you also added the sshagent and unix socket dependencies, but if they're really necessary we can add them back in. 
Root issue is that 5.8.0 of jgit the Jsch/SSH implementation (JschSessionFactory) was split out into a new jar. As a result this jar needs to be included as the GitScmDownloader configuration needs for it to be available for clones to work properly.
> Fix JGit integration

- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/util/MapConverter.java
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/SpringTestMethodBodyBuildersSpec.groovy
Relates to [#1630](https://github.com/spring-cloud/spring-cloud-contract/issues/1630)
I added a test that reproduces the issue and added a fix that achieves the expected behavior.
@marcingrzejszczak in the ticket you say `it should work with sets`, 
but a set is an unordered collection, but arrays in JSON are ordered.
Do we check the order of elements in JSON?  If not, just accept my PR :)
If yes, I'm hesitating that we can treat sets as lists. Maybe we have to check `contains` for sets, but not `equals`.
I can work on it, but I need this to be clarified.
Also
`SingleTestGeneratorSpec` fails in the `main` branch as well, so it's not related to my changes.
> #1630 Fix assertion for Map<String, Set<String>>

- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/dsl/wiremock/WireMockRequestStubStrategy.java
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/dsl/wiremock/WireMockGroovyDslSpec.groovy
Correctly handle client specific DslProperties (e.g. anyAlphanumeric()) in request headers, cookies, etc. by extracting the client value before writing the stub value.
> Fix handling of ClientDslProperties when generating wiremock stubs

- docs/src/main/asciidoc/using.adoc
Fixes https://github.com/spring-cloud/spring-cloud-contract/issues/1746
I referred to the [Consumer setup](https://docs.spring.io/spring-cloud-contract/docs/current/reference/html/using.html#flows-provider-git-consumer) JUnit5 Extension example while making the change.
Applying the change to the `3.1.x` branch as required.
> docs: Update JUnit5 example, fixes gh-1746

- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/builder/RestAssuredGiven.java
- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/builder/SpockExplicitMultipartGiven.java
- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/builder/SpockWebTestClientMultipartGiven.java
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/SpringTestMethodBodyBuildersSpec.groovy
Currently, the multipart support for EXPLICIT and WEBCLIENTTEST modes in Spock is missing. This PR adds the support.
Fixes #1667
> fix #1667: Add missing multipart support in Spock

- spring-cloud-contract-tools/spring-cloud-contract-converters/src/test/groovy/org/springframework/cloud/contract/verifier/wiremock/DslToWireMockClientConverterSpec.groovy
- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/dsl/wiremock/BaseWireMockStubStrategy.java
- spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/dsl/wiremock/WireMockResponseStubStrategySpec.groovy
Currently, numbers, booleans and null inside arrays are double-quoted when converting DSL into stubs, which results in generating incorrect json stubs for WireMock. This PR fixes it.
Fixes #1656.
> fix #1656: Add missing support for JSON values inside arrays in WireMockStub

- spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockRestServiceServer.java
- spring-cloud-contract-wiremock/src/test/java/org/springframework/cloud/contract/wiremock/WiremockMockServerApplicationTests.java
- spring-cloud-contract-wiremock/src/test/resources/mappings/url-simple-path-pattern-with-leading-slash.json
- spring-cloud-contract-wiremock/src/test/resources/mappings/url-simple-path-pattern-without-leading-slash.json
Current behaviour :
* base URL = http://foo.bar/
* url = http://foo.bar/my/api
gives => my/api
Fixed behaviour : 
* base URL = http://foo.bar/
* url = http://foo.bar/my/api
gives => /my/api
> Fixed relative URL computation in wIthoutBaseUrl

- spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockSpring.java
WireMockSpring.config() replaced by WireMockSpring.options() at javadoc
> Javadoc fixed

- spring-cloud-contract-tools/spring-cloud-contract-converters/src/test/groovy/org/springframework/cloud/contract/verifier/converter/RecursiveFilesConverterSpec.groovy
- spring-cloud-contract-tools/spring-cloud-contract-converters/src/test/resources/converter/dir3/Account creating.yml
- spring-cloud-contract-tools/spring-cloud-contract-converters/src/test/resources/converter/dir3/Test route.yml
- spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/converter/YamlToContracts.java
> Fixes gh-1876

- spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockRestTemplateConfiguration.java
- spring-cloud-contract-wiremock/src/test/java/org/springframework/cloud/contract/wiremock/AutoConfigureWireMockHttpsPortApplicationTests.java
- spring-cloud-contract-wiremock/src/test/java/org/springframework/cloud/contract/wiremock/WiremockTestsApplication.java
- Added test with Apache client and HTTPS
- Added test with Apache client and HTTPS and additional interceptor (original issue)
- Implementation is done with ReflectionUtils :( as I was not able to find better way (InterceptingClientHttpRequestFactory expose only "createRequest")
closes #1868
> Relaxed SSL validation with RestTemplate interceptors

- spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/restdocs/ContractDslSnippet.java
- spring-cloud-contract-wiremock/src/main/resources/org/springframework/restdocs/templates/default-dsl-contract-only.snippet
- spring-cloud-contract-wiremock/src/test/java/org/springframework/cloud/contract/wiremock/restdocs/ContractDslSnippetTests.java
Allows specifying priority eg
```
SpringCloudContractRestDocs.dslContract(Maps.of("priority", 1))))
```
and makes it possible to override the dsl template
```
new ContractDslSnippet(){
@Override
protected String getTemplate() {
return "custom-dsl-contract";
}
}));
```
(template must live in resources/org/springframework/restdocs/templates)
Fixes gh-1818
> Adds support to specify priority and allow for template override

- spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/file/ResourcesFileSource.java
I had an issue with a broken configuration, and it would have helped immensely to be able to observe what paths were tried, and which exceptions were thrown, if any.
This patch adds a logger, some debug logging when traversing the sources configuration, and if any exceptions are thrown they are logged if debug is switched on. This will hopefully make it easier to grasp what is wrong with the configuration.
> Improving observability when debugging broken wiremock configurations

- spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockTestExecutionListener.java
- spring-cloud-contract-wiremock/src/test/java/org/springframework/cloud/contract/wiremock/TestExecutionListenerAllowsOtherBeforeActionsTest.java
Closes #1995 
In the end I choose to use a different test execution phase `prepareTestInstance` which is called after `applicationContext` is available, since that whole method depends on it being available.
> Use prepareTestInstance phase instead of beforeTestClass phase

- spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockApplicationListener.java
- spring-cloud-contract-wiremock/src/test/java/org/springframework/cloud/contract/wiremock/AutoConfigureWireMockApplicationTests.java
Fixes https://github.com/spring-cloud/spring-cloud-contract/issues/2035
> Fix GH-2035 AutoConfigureWiremock with a pre-defined custom port always defaults to port 8080

- docker/spring-cloud-contract-docker/project/build.gradle
Using springcloud/spring-cloud-contract to run external contracts fails due to:
```
org.gradle.internal.execution.WorkValidationException: A problem was found with the configuration of task ':generatePomFileForMavenPublication' (type 'GenerateMavenPom').
- Gradle detected a problem with the following location: '/spring-cloud-contract/build/publications/maven/pom-default.xml'.
Reason: Task ':copyOutput' uses this output of task ':generatePomFileForMavenPublication' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
Possible solutions:
1. Declare task ':generatePomFileForMavenPublication' as an input of ':copyOutput'.
2. Declare an explicit dependency on …
```
> Fix docker gradle build

- docker/spring-cloud-contract-stub-runner-docker/run.sh
Also pass the arguments along to the java execution
Previously the arguments were silently dropped
> fix: Use exec for better PID 1 handling
