spring-cloud-contract-dependencies/pom.xml
spring-cloud-contract-tools/spring-cloud-contract-maven-plugin/pom.xml

we want to be consistent with Spring Boot CLI
fixes #75

Changing aether version

---

spring-cloud-contract-tools/spring-cloud-contract-maven-plugin/src/main/java/org/springframework/cloud/contract/maven/verifier/RunMojo.java

this allows to easy convert and run stub server from project

stubs mappings directory should be the same for convert and run mojo.

---

docs/src/main/asciidoc/README.adoc

Minor typo in README

---

README.adoc
samples/pom.xml
samples/standalone/dsl/http-client/pom.xml
samples/standalone/dsl/http-server/pom.xml
samples/standalone/messaging/stream-sink/pom.xml
samples/standalone/messaging/stream-source/pom.xml
samples/standalone/restdocs/http-client/pom.xml
samples/standalone/restdocs/http-server/pom.xml
spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/ContractDownloader.java
spring-cloud-contract-stub-runner/src/test/groovy/org/springframework/cloud/contract/stubrunner/ContractDownloaderSpec.groovy
spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/pom.xml
spring-cloud-contract-tools/spring-cloud-contract-maven-plugin/src/test/java/org/springframework/cloud/contract/maven/verifier/PluginIT.java
spring-cloud-contract-tools/spring-cloud-contract-maven-plugin/src/test/java/org/springframework/cloud/contract/maven/verifier/PluginUnitTest.java
spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/util/RegexpBuilders.groovy
tests/spring-cloud-contract-stub-runner-camel/src/test/groovy/org/springframework/cloud/contract/stubrunner/messaging/camel/CamelStubRunnerSpec.groovy
tests/spring-cloud-contract-stub-runner-integration/src/test/groovy/org/springframework/cloud/contract/stubrunner/messaging/integration/IntegrationStubRunnerSpec.groovy
tests/spring-cloud-contract-stub-runner-stream/src/test/groovy/org/springframework/cloud/contract/stubrunner/messaging/stream/StreamStubRunnerSpec.groovy

* had to ignore some tests for Windows due to absurd exceptions
* fixed escaping path for directory matching
fixes #98

Making Windows build pass

---

README.adoc
docs/src/main/asciidoc/verifier/stubrunner.adoc
spring-cloud-contract-stub-runner/README.adoc
spring-cloud-contract-stub-runner/pom.xml
spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/AetherFactories.java
spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/AetherStubDownloader.java
spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/Arguments.java
spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/ContractDownloader.java
spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/StubDownloader.java
spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/StubRunnerFactory.java
spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/StubRunnerMain.java
spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/StubRunnerOptions.java
spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/StubRunnerOptionsBuilder.java
spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/junit/StubRunnerRule.java
spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/spring/StubRunnerConfiguration.java
spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/spring/StubRunnerProperties.java
spring-cloud-contract-stub-runner/src/test/groovy/org/springframework/cloud/contract/stubrunner/AetherStubDownloaderSpec.groovy
spring-cloud-contract-stub-runner/src/test/groovy/org/springframework/cloud/contract/stubrunner/ContractDownloaderSpec.groovy
spring-cloud-contract-stub-runner/src/test/groovy/org/springframework/cloud/contract/stubrunner/StubRunnerFactorySpec.groovy
spring-cloud-contract-stub-runner/src/test/resources/simulation.json

Continued from https://github.com/spring-cloud/spring-cloud-contract/pull/142
@mogronalol @yacekmm

Issues #110 user pass

---

spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/restdocs/WireMockSnippet.java
spring-cloud-contract-wiremock/src/test/java/org/springframework/cloud/contract/wiremock/restdocs/WireMockSnippetTests.java

Implement JSON matching with JSON Content-Type

---

spring-cloud-contract-dependencies/pom.xml
spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/groovy/org/springframework/cloud/contract/verifier/plugin/SpringCloudContractVerifierGradlePlugin.groovy
spring-cloud-contract-tools/spring-cloud-contract-maven-plugin/src/test/projects/complex-configuration/pom.xml
spring-cloud-contract-tools/spring-cloud-contract-maven-plugin/src/test/projects/plugin-extension/pom.xml
spring-cloud-contract-tools/spring-cloud-contract-maven-plugin/src/test/projects/spring-boot-groovy/pom.xml
spring-cloud-contract-tools/spring-cloud-contract-maven-plugin/src/test/projects/spring-boot-java/pom.xml
spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/dsl/wiremock/WireMockRequestStubStrategy.groovy
spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/util/DelegatingJsonVerifiable.java
spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/util/JsonToJsonPathsConverter.groovy
spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/util/MethodBufferingJsonVerifiable.java
spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/MockMvcMethodBodyBuilderSpec.groovy

with this change we're using new JSONAssert that allows to check if an array is empty
fixes #203

Asserting empty array in the response

---

spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/PatternValueDslProperty.groovy
spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/RegexPatterns.groovy
spring-cloud-contract-spec/src/test/groovy/org/springframework/cloud/contract/spec/internal/RegexPatternsSpec.groovy
spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/JaxRsClientMethodBuilderSpec.groovy
spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/MockMvcMethodBodyBuilderSpec.groovy

Added:
iso8601WithOffset which handles iso8601 date time with timezone date validation
nonBlankString which handles string that aren't "" and also just whitespace
nonEmptyString which handles "" strings
anyOf(String...) which handles enumerated style attributes for validation

gh-245: Created new DslProperty creation methods

---

samples/wiremock-jetty/src/test/java/com/example/WiremockServerApplicationTests.java
samples/wiremock-tomcat/src/test/java/com/example/WiremockServerApplicationTests.java
spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/SpringBootHttpServerFactory.java
spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/TomcatFaultInjector.java
spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/TomcatFaultInjectorFactory.java
spring-cloud-contract-wiremock/src/test/java/org/springframework/cloud/contract/wiremock/WiremockServerApplicationTests.java

It would be good to have the same features for Tomcat and Undertow.
See gh-270.

Add a fault injector if server is jetty

---

pom.xml

Bumped Camel

---

docs/src/main/asciidoc/verifier/contract.adoc

I only changed line 483. GitHub is highlighting line 1202. which I didn't do anything with, I hope it is not a CRLF change or sth.

Updated description of byType testMatcher

---

pom.xml
samples/standalone/restdocs/http-client/pom.xml
samples/standalone/restdocs/http-server/pom.xml
spring-cloud-contract-wiremock/pom.xml
spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/restdocs/WireMockRestAssuredConfiguration.java
spring-cloud-contract-wiremock/src/main/resources/META-INF/spring.factories
spring-cloud-contract-wiremock/src/test/java/org/springframework/cloud/contract/wiremock/WiremockServerRestAssuredApplicationTests.java

Add support for restassured with restdocs

---

spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/spring/cloud/consul/ConsulStubsRegistrar.java
spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/spring/cloud/consul/StubRunnerSpringCloudConsulAutoConfiguration.java
spring-cloud-contract-stub-runner/src/test/groovy/org/springframework/cloud/contract/stubrunner/spring/cloud/consul/StubRunnerSpringCloudConsulAutoConfigurationSpec.groovy

#491 - Stubs are registered to consul with localhost

#491 - Stubs are registered to consul with localhost

---

spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/spring/cloud/consul/ConsulStubsRegistrar.java
spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/spring/cloud/consul/StubRunnerSpringCloudConsulAutoConfiguration.java
spring-cloud-contract-stub-runner/src/test/groovy/org/springframework/cloud/contract/stubrunner/spring/cloud/consul/StubRunnerSpringCloudConsulAutoConfigurationSpec.groovy

@marcingrzejszczak I push the commits of issue #491 with no proper git config and as such it created bad commiter info (non existing user), this PR fixes that if you can please check it out

Fix bad commiter info from #491

---

spring-cloud-contract-tools/spring-cloud-contract-spec-pact/src/main/groovy/org/springframework/cloud/contract/verifier/spec/pact/PactContractConverter.groovy
spring-cloud-contract-tools/spring-cloud-contract-spec-pact/src/test/groovy/org/springframework/cloud/contract/verifier/spec/pact/PactContractConverterSpec.groovy
spring-cloud-contract-tools/spring-cloud-contract-spec-pact/src/test/resources/pact/pact_509.json

fixed error in unit test data and replaced request matcher with response matcher (#511)

matcher now correctly matches response instead of request  

---

spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/MethodBuilder.groovy
spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/util/NamesUtil.groovy
spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/MethodBuilderSpec.groovy
spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/util/NamesUtilSpec.groovy

replace invalid characters in generated method names with underscore

---

docs/src/main/asciidoc/verifier_faq.adoc

Updated doc for messaging contracts

[#500] Messaging contracts per topic

---

README.adoc
docs/src/main/asciidoc/verifier_faq.adoc
docs/src/main/asciidoc/verifier_introduction.adoc
docs/src/main/asciidoc/verifier_messaging.adoc

Add short tours

---

docs/src/main/asciidoc/verifier_introduction.adoc

Olga Maciaszek-Sharma added very nice content, in the form of a three-second and a three-minute introduction for the verifier. I edited her additions to conform to our usual standards and corporate voice.

 Editing pass for new content

---

spring-cloud-contract-stub-runner/src/main/resources/META-INF/additional-spring-configuration-metadata.json

Add missing configuration properties metadata for stub-runner

---

spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/JUnitMessagingMethodBodyBuilder.groovy
spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/SpockMessagingMethodBodyBuilder.groovy
spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/MessagingMethodBodyBuilderSpec.groovy

Generated messaging tests could create compilation errors for certain regexes in headers

---

spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/Input.groovy
spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/OutputMessage.groovy
spring-cloud-contract-spec/src/test/groovy/org/springframework/cloud/contract/spec/internal/InputSpec.groovy
spring-cloud-contract-spec/src/test/groovy/org/springframework/cloud/contract/spec/internal/OutputMessageSpec.groovy

Added the missing $() convenience method for messaging contracts

---

docs/src/main/asciidoc/verifier_contract.adoc

Stubs matchers - always about REQUESTS;
Verifier matchers - always about RESPONSES.

Matchers documentation improvements

---

spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/JUnitMessagingMethodBodyBuilder.groovy
spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/JaxRsClientJUnitMethodBodyBuilder.groovy
spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/JaxRsClientSpockMethodRequestProcessingBodyBuilder.groovy
spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/MockMvcSpockMethodRequestProcessingBodyBuilder.groovy
spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/RestAssuredJUnitMethodBodyBuilder.groovy
spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/SpockMessagingMethodBodyBuilder.groovy
spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/MessagingMethodBodyBuilderSpec.groovy
spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/MockMvcMethodBodyBuilderSpec.groovy

A response header should be verified against an execution property

---

spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/util/JsonToJsonPathsConverter.groovy
spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/MockMvcMethodBodyBuilderSpec.groovy
spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/util/JsonToJsonPathsConverterSpec.groovy

Added assertion for empty map/object to autogenerated test

---

spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/PatternValueDslProperty.groovy
spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/dsl/wiremock/WireMockResponseStubStrategySpec.groovy

Generated numbers shouldn't be quoted in the stub

---

spring-cloud-contract-tools/spring-cloud-contract-maven-plugin/src/site/asciidoc/usage.adoc

Fix `pluginGroups` entry info. Fix plugin call examples. Add info about necessary directory setup.

Fix `pluginGroups` entry info. Fix plugin call examples. Add info about

---

pom.xml

Remove mockito-core from dependencyManagement

Remove mockito-core from dependencyManagement

---

spring-cloud-contract-starters/spring-cloud-starter-contract-stub-runner/pom.xml

Made stream binder optional

---

spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/dsl/wiremock/BaseWireMockStubStrategy.groovy
spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/dsl/WireMockGroovyDslSpec.groovy

Workaround for JsonObject and JsonBuilder processing of json-like strings.

Remove duplicated backslashes. Fixes gh-667

---

.settings.xml
samples/standalone/contracts/src/assembly/contracts.xml
samples/standalone/restdocs/http-server/src/assembly/stub.xml
samples/standalone/webclient/http-server/src/assembly/stub.xml
spring-cloud-contract-tools/spring-cloud-contract-maven-plugin/src/test/projects/basic-remote-contracts/pom-with-repo.xml
tests/samples-messaging-integration/src/main/resources/integration-context.xml
tests/spring-cloud-contract-stub-runner-integration/src/test/resources/integration-context.xml

This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
https://maven.apache.org/xsd/assembly-1.1.3.xsd ([https](https://maven.apache.org/xsd/assembly-1.1.3.xsd) result 200).
https://maven.apache.org/xsd/maven-4.0.0.xsd ([https](https://maven.apache.org/xsd/maven-4.0.0.xsd) result 200).
https://www.springframework.org/schema/beans/spring-beans.xsd ([https](https://www.springframework.org/schema/beans/spring-beans.xsd) result 200).
https://www.springframework.org/schema/integration/spring-integration.xsd …

URL Cleanup

---

spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/converter/YamlContractConverter.groovy
spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/converter/YamlContractConverterSpec.groovy
spring-cloud-contract-verifier/src/test/resources/yml/oa3/openapi_petstore.yml

parse file and return false is parse fails. Closes #1036

Updating YamlContractConverter to during isAccepted method, to

---

spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockConfiguration.java

Obvious Fix
Fix the bug #1075 with input stream not being closed

fix leaking file handles from loaded stubs (#1075)

---

spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/FromFileProperty.groovy
spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/dsl/wiremock/WireMockGroovyDslSpec.groovy
spring-cloud-contract-verifier/src/test/resources/classpath/request.xml

Fix for the issue #1105
body file('someXmlFile.xml') works without exception now

Fixed issue with content is not allowed in prolog for body from the xml file

---

spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/dsl/wiremock/WireMockRequestStubStrategy.groovy
spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/dsl/wiremock/WireMockGroovyDslSpec.groovy

Fixed bug with explicit content type and any matching strategy at the body section gh-1106

Matching strategy at body and contentType issue

---

spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/util/JsonToJsonPathsConverter.groovy
spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/MockMvcMethodBodyBuilderWithMatchersSpec.groovy

Recognise arrays by regex and not only `[*]` literal.

---

spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/assertion/CollectionAssert.java
spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/assertion/CollectionAssertTests.java

Signed-off-by: Olga Maciaszek-Sharma <olga.maciaszek@gmail.com>

Fix flattened size counter. Fixes gh-1108.

---

specs/spring-cloud-contract-spec-kotlin/src/main/kotlin/org/springframework/cloud/contract/spec/internal/InputDsl.kt
specs/spring-cloud-contract-spec-kotlin/src/main/kotlin/org/springframework/cloud/contract/spec/internal/OutputMessageDsl.kt
specs/spring-cloud-contract-spec-kotlin/src/test/kotlin/org/springframework/cloud/contract/spec/ContractTests.kt

Enhanced Kotlin DSL

---

spring-cloud-contract-tools/spring-cloud-contract-pact/src/main/groovy/org/springframework/cloud/contract/verifier/spec/pact/BodyConverter.groovy
spring-cloud-contract-tools/spring-cloud-contract-pact/src/test/groovy/org/springframework/cloud/contract/verifier/spec/pact/PactContractConverterSpec.groovy

Fixed issues with Pact conversion after upgrade

---

docs/src/main/asciidoc/sagan-boot.adoc

Documentation - Update title style in section 2.2.

---

spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/server/EnableStubRunnerServer.java
spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/server/StubRunnerAutoConfiguration.java
spring-cloud-contract-stub-runner/src/test/java/org/springframework/cloud/contract/stubrunner/server/StubRunnerAutoConfigurationTests.java
spring-cloud-contract-verifier/src/test/java/org/springframework/cloud/contract/verifier/messaging/amqp/ContractVerifierAmqpAutoConfigurationTests.java
spring-cloud-contract-verifier/src/test/java/org/springframework/cloud/contract/verifier/messaging/boot/AutoConfigureMessageVerifierTests.java
spring-cloud-contract-verifier/src/test/java/org/springframework/cloud/contract/verifier/messaging/camel/ContractVerifierCamelConfigurationTests.java
spring-cloud-contract-verifier/src/test/java/org/springframework/cloud/contract/verifier/messaging/integration/ContractVerifierIntegrationConfigurationTests.java
spring-cloud-contract-verifier/src/test/java/org/springframework/cloud/contract/verifier/messaging/jms/ContractVerifierJmsConfigurationTests.java
spring-cloud-contract-verifier/src/test/java/org/springframework/cloud/contract/verifier/messaging/kafka/ContractVerifierKafkaConfigurationTests.java
spring-cloud-contract-verifier/src/test/java/org/springframework/cloud/contract/verifier/messaging/noop/NoOpContractVerifierAutoConfigurationTests.java
spring-cloud-contract-verifier/src/test/java/org/springframework/cloud/contract/verifier/messaging/stream/ContractVerifierStreamAutoConfigurationTests.java

Enhanced messaging support for stubrunner

---

docs/src/main/asciidoc/_project-features-contract.adoc
docs/src/main/asciidoc/_project-features-messaging.adoc
docs/src/main/asciidoc/_project-features-stubrunner.adoc
docs/src/main/asciidoc/docker-project.adoc
docs/src/main/asciidoc/getting-started.adoc
docs/src/main/asciidoc/ghpages.sh
docs/src/main/asciidoc/gradle-project.adoc
docs/src/main/asciidoc/howto.adoc
docs/src/main/asciidoc/maven-project.adoc
docs/src/main/asciidoc/project-features.adoc
docs/src/main/asciidoc/using.adoc

Wording changes

---

specs/spring-cloud-contract-spec-java/src/main/java/org/springframework/cloud/contract/spec/internal/RegexPatterns.java
spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/JaxRsClientMethodBuilderSpec.groovy
spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/MessagingMethodBodyBuilderSpec.groovy
spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/SpringTestMethodBodyBuildersSpec.groovy

no length limit in ISO8601_WITH_OFFSET second's decimal fraction

---

spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/XmlBodyVerificationBuilder.java
spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/util/xml/XmlToXPathsConverter.groovy
spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/util/ContractVerifierUtil.java
spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/util/xml/DOMNamespaceContext.java
spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/converter/YamlContractConverterSpec.groovy
spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/util/xml/XmlToXPathsConverterSpec.groovy
spring-cloud-contract-verifier/src/test/java/org/springframework/cloud/contract/verifier/builder/XmlBodyVerificationBuilderTest.java
spring-cloud-contract-verifier/src/test/java/org/springframework/cloud/contract/verifier/util/ContractVerifierUtilTest.java
spring-cloud-contract-verifier/src/test/resources/yml/contract_rest_named_xml.yml

This PR updates all places where xpath is used to be able to handle xml with name spaces.

bug: handle xml with namespaces for validations #1427

---

docs/src/test/java/org/springframework/cloud/contract/docs/AdditionalResourcesGenerationTests.java

Fixes a couple of formatting issues that should be included when the
doc-generation code is moved out of a test.

Change related to issue 1483

---

spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockConfiguration.java
spring-cloud-contract-wiremock/src/test/java/org/springframework/cloud/contract/wiremock/AutoConfigureWireMockConfigurationMultipleCustomizerTests.java

Support multiple WireMockConfigurationCustomizers

---

docs/src/main/asciidoc/_project-features-contract.adoc
spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/ContractsCopyTask.java
spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/SpringCloudContractVerifierGradlePlugin.java

Several fixes for contracts that are fetched remotely via Git.

Fixes for remote contracts

---

spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/SpringCloudContractVerifierGradlePlugin.java

Fix stubsDir for publishStubsToScmTask.

---

specs/spring-cloud-contract-spec-java/src/main/java/org/springframework/cloud/contract/spec/internal/PatternValueDslProperty.java
spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/SpringTestMethodBodyBuildersSpec.groovy

Generates random boolean request value for aBoolean()

---

docs/src/main/asciidoc/_building.adoc

Added a section "Cloning the repository on Windows" for issue#1567

---

spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockTestExecutionListener.java
spring-cloud-contract-wiremock/src/test/java/org/springframework/cloud/contract/wiremock/AutoConfigureWireMockWithResetAfterEachTestNestedApplicationTests.java

Allows @Nested tests to use Wiremock by searching enclosing class for @AutoConfigureWiremock 
Fixes gh-1610

Searches enclosing class for @AutoConfigureWiremock

---

spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockRestServiceServer.java
spring-cloud-contract-wiremock/src/test/java/org/springframework/cloud/contract/wiremock/WiremockMockServerApplicationTests.java
spring-cloud-contract-wiremock/src/test/resources/mappings/resource-with-base64-body.json
spring-cloud-contract-wiremock/src/test/resources/mappings/resource-with-json-body.json

Support for jsonBody and base64Body Fixes gh-1644

---

spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockApplicationListener.java
spring-cloud-contract-wiremock/src/test/java/org/springframework/cloud/contract/wiremock/AutoConfigureWireMockOnlyHttpsPortApplicationTests.java
spring-cloud-contract-wiremock/src/test/java/org/springframework/cloud/contract/wiremock/AutoConfigureWireMockOnlyRandomPortHttpsApplicationTests.java

Random https port in annotation AutoConfigureWireMock is broken issue - fix

#1633 - Random https port in annotation AutoConfigureWireMock is broken issue

---

spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/builder/MockMvcHeadersGiven.java
spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/MethodBodyBuilderSpec.groovy

Fix request headers occurring after absent header not being added to generated test method

---

docs/src/main/asciidoc/gradle-project.adoc

Fixing typo in gradle example.

Fixed typo in gradle example

---

spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/messaging/amqp/SpringAmqpStubMessages.java
spring-cloud-contract-verifier/src/test/java/org/springframework/cloud/contract/verifier/messaging/amqp/SpringAmqpStubMessagesTests.java

@pivotal-cla This is an Obvious Fix

fix #1705: AMQP stub runner NullPointerException

---

spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/messaging/jms/JmsStubMessages.java
spring-cloud-contract-verifier/src/test/java/org/springframework/cloud/contract/verifier/messaging/jms/JmsStubMessagesTests.java

@pivotal-cla This is an Obvious Fix

fix #1711: Possible NPE in JMS stubs

---

spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/build.gradle

Enable SSH Agent support.

---

spring-cloud-contract-tools/spring-cloud-contract-pact/src/main/java/org/springframework/cloud/contract/verifier/spec/pact/PactMetaData.java
spring-cloud-contract-tools/spring-cloud-contract-pact/src/main/java/org/springframework/cloud/contract/verifier/spec/pact/RequestResponsePactCreator.java
spring-cloud-contract-tools/spring-cloud-contract-pact/src/test/groovy/org/springframework/cloud/contract/verifier/spec/pact/PactMetaDataTests.java
spring-cloud-contract-tools/spring-cloud-contract-pact/src/test/resources/contracts/shouldConvertAllGenerators.groovy
spring-cloud-contract-tools/spring-cloud-contract-pact/src/test/resources/contracts/shouldConvertAllGenerators.json

Add context field for the request to be able to generate providerStates when a Contract for HTTP to a PACT.

Add capability to set initial request context. Fixes gh-1740.

---

spring-cloud-contract-tools/spring-cloud-contract-maven-plugin/src/main/java/org/springframework/cloud/contract/maven/verifier/GenerateTestsMojo.java

Do not skip code generation on skipTests

---

spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/util/MetadataUtil.java
spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/messaging/amqp/SpringAmqpStubMessagesSpec.groovy
spring-cloud-contract-verifier/src/test/java/org/springframework/cloud/contract/verifier/messaging/amqp/AmqpMetadataTests.java

Harden detection of InaccessibleObjectException in MetadataUtil

---

spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/converter/YamlToContracts.java
spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/converter/YamlContractConverterSpec.groovy

Use the same implementation for url and urlPath during parsing queryParameters

#1778 properly resole query parameters for url and urlPath property in YAML files

---

spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/converter/ContractsToYaml.java
spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/converter/DslToYamlContractConverterSpec.groovy

Add priority property to converted contract in yaml

Add priority property to converted contract in yaml

---

docs/src/main/asciidoc/getting-started.adoc
docs/src/main/asciidoc/using.adoc

Fixed some adoc grammar
Related to #1817

fix: adoc code highlighting syntax (#1817)

---

spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/converter/ContractsToYaml.java
spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/converter/DslToYamlContractConverterSpec.groovy

Fix NPE while convert contracts to YAML without request headers

Fixes gh-1873

---

docs/src/main/asciidoc/_project-features-flows.adoc

Adds some supporting documentation for GH-1818

---

samples/standalone/dsl/http-server/build.gradle
spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/SpringCloudContractVerifierGradlePlugin.java

Add dependency on copyContracts

---

samples/standalone/dsl/http-server/build.gradle

Remove `useJUnitPlatform()` as this is the default from the Gradle plugin

---

spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/StubRunnerExecutor.java

I've tested locally with my use case and the null body message is sent fine.

https://github.com/spring-cloud/spring-cloud-contract/issues/1935

---

spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/SpringCloudContractVerifierGradlePlugin.java

In particular this addresses:
* `JavaPluginConvention` -> `JavaPluginExtension` which has been available since Gradle 4.10
* `GroovySourceSet` -> `GroovySourceDirectorySet` which is available beginning with Gradle 7.1. Given the Spring Boot Gradle Plugin as of 3.0.0 requires Gradle 7.4 as the minimum allowable version, it is safe to make this jump.

Cleanup Gradle deprecations

---

spring-cloud-contract-shade/pom.xml

Reverts spring-cloud/spring-cloud-contract#2077 - we'll need to do it once main has 4.2.0 in it

Revert "Update pom.xml"

---

.github/CONTRIBUTING.md
README.adoc

PR updates the Code of Conduct reference in `README.md` and `CONTRIBUTING.md`.

Update Code of Conduct reference
